module.exports = {
  User: require('./User'),
  Organization: require('./Organization'),
  Building: require('./Building'),
  Tower: require('./Tower'),
  Unit: require('./Unit'),
  Resident: require('./Resident'),
  ServiceCategory: require('./ServiceCategory'),
  ServiceProvider: require('./ServiceProvider'),
  Service: require('./Service'),
  ServiceRequest: require('./ServiceRequest'),
  Facility: require('./Facility'),
  FacilityBooking: require('./FacilityBooking'),
  Announcement: require('./Announcement'),
  Publication: require('./Publication'),
  Message: require('./Message'),
  QuickAction: require('./QuickAction'),
  EmergencyContact: require('./EmergencyContact'),
  Payment: require('./Payment'),
  VisitorParking: require('./VisitorParking'),
  ServiceSuspension: require('./ServiceSuspension'),
};
